package communication.base;

public enum MessageType{
    FENCE_STATUS,
    PASSENGER_ENTERED_VEHICLE,
    PASSENGER_EXITED_VEHICLE,
    EMERGENCY_OVERRIDE,
    AUDIO_BROADCAST,
    EMERGENCY_HANDLED,
    VEHICLE_INITIALIZATION,
    T_REX_STATUS,
    DEVICE_STATUS_UPDATE,
    VEHICLE_STATUS,
    OPERATOR_EMERGENCY_REQUEST,
    EMERGENCY_DEESCALATION,
    PASSENGER_REGISTRATION,
    PASSENGER_DEREGISTRATION,
    TOKEN_DISPLAY_MESSAGE,
    RECEIPTS,
    REQUEST_RECEIPTS,
    TOKEN_INITIALIZED,
    TOKEN_KIOSK_STATUS,
    TOKEN_STATUS,
    GUEST_LOCATION
}
